[project]
name = "max-stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.0.0",
    "polars>=1.35.1",
    "typer-slim>=0.20.0",
    "vegafusion>=2.0.3",
    "vl-convert-python>=1.8.0",
]
